name: Postgres-db

on:
  push:
    branches: [main]
    paths:
      - "helm/database/**"  
  workflow_dispatch:

jobs:
  deploy-db:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: deploy
      run: helm install postgres ./helm/database
